Update main.cpp
The call to check clobbers the error message (horray for global variables).
This patch saves the error message so that it can be printed.

Before:
error: {"code":-25,"message":""}

After: